version: "2.1"
services:

  inventory-client:
    build: .
    volumes:
      - ./:/cern_webinfra_inventory_client
    environment:
    # Inventory
      INVENTORY_URL: http://inventory:8080

  postgres:
    image: registry.access.redhat.com/rhscl/postgresql-94-rhel7
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: verystr0ngpassword
      POSTGRESQL_DATABASE: webinfra

  inventory:
    image: wklm/cern-webinfra-inventory
    ports:
      - "8080:8080"
    environment:
     # Postgres
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: verystr0ngpassword
      POSTGRESQL_DATABASE: webinfra
    depends_on:
      - postgres 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
